### ISSUE TITLE
What Build process does & Glass material for AR

### ISSUE THREAD

**Issue by RaiaN** [GoogleCloudPlatform/immersive-stream-for-xr-templates#20]
Hey,

I was looking into the template project and noticed that:
1) Some materials are not being used (i.e. magic window one)
2) ToBuild folder is being uploaded to the bucket
3) Car windows use dummy glass material

Do you do some asset replacement during the build process time to make sure glass material is rendered correctly? As well as configuring lights in special way so that they don't affect translucency in a bad way in AR?

**Comment by cs-grasso** [comment]
Hi,

We use the *ToBuild* folder to replace some of the assets during the build process. The files in this folder shouldn't be modified because this might cause builds to fail.

The materials and assets used for the Autos demo are all named *Dummy* because these are intended to be replaced once creators import their own assets. We do not replace the car window glass material at any time.

Some assets that are part of the template and are not being used in any of the maps are examples of features for which we haven't created demos yet but were requested by some creators to use in their projects. We'll include a Magic Window demo soon.
